# -*- coding: utf-8 -*-
"""HR database EDA and ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rK_m3SQ2o8w4PC1Kqc7NprOoEjubDB5O
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("HR database1.csv")
df.head(5)

df.shape   ## total rows and columns of the dataset

df.info()    ## information related to the columns
df.isnull().sum().sum()  ## no null values present

df.duplicated().sum()    ### No duplicates

"""## Outliers checking"""

num_cols = df.select_dtypes(include="number").columns

Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

outlier_counts = {}

for col in num_cols:
    lower = Q1[col] - 1.5 * IQR[col]
    upper = Q3[col] + 1.5 * IQR[col]
    outlier_counts[col] = ((df[col] < lower) | (df[col] > upper)).sum()

print(pd.Series(outlier_counts).sort_values(ascending=False))

num_cols = df.select_dtypes(include="number").columns

outlier_rows = []

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_rows.append(df[(df[col] < lower) | (df[col] > upper)])

outlier_df = pd.concat(outlier_rows).drop_duplicates()

outlier_df.head()

"""## Outliers cliping"""

for col in df.select_dtypes(include="number").columns:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1

  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR


  df[col] = df[col].clip(lower, upper)

"""“Outliers were handled using IQR-based winsorization. Instead of removing data points, extreme values were capped at statistically defined bounds computed from the training set. This reduced noise and prevented tree-based models from overfitting rare extreme cases, resulting in improved generalization.”"""

sns.boxplot(x=df["MonthlyIncome"])
plt.show()                                    ### Outliers has been cliped.

"""## Over time shows higer attrition rate"""

rate_df =(df.groupby("OverTime")["Attrition"].apply(lambda x:(x == "Yes").mean()).reset_index(name="Attrition Rate"))

sns.barplot(data=rate_df, x="OverTime", y="Attrition Rate")
plt.title("Attrition Rate by OverTime")
plt.ylabel("Attrition Rate")
plt.show()

print(rate_df)

"""## Young early carrier people shows highest attrition"""

print("Attrition by years in curremt job role:\n", df[df["Attrition"]=="Yes"]["YearsInCurrentRole"].value_counts())  ## Early carrier attrition count

df[df["Attrition"] == "Yes"][["TotalWorkingYears", "Age"]].value_counts()  ### people with lest total working years shows more attrition and these people are young.

"""##

## Total working Years of 5 - 10 faces highest attrition
"""

sns.histplot(data=df,x="TotalWorkingYears", hue="Attrition", bins=20, kde=True)
plt.title("Distribution of Total Working Years by Attrition")
plt.show()

"""## MontlyIncome plays a role in Job level and role based attrition  """

df[df["Attrition"]=="Yes"][["JobRole","JobLevel"]].value_counts()   ### sales, laaoratory technician has highest attrition count
                                                                     ### Joblevel 1, 2, 3 has highest attrition count.

df.groupby([ "JobLevel", "JobRole", "Attrition"])["MonthlyIncome"].sum().sort_values(ascending=True)
### MonthlyIncome does plays a role in in Attrition.

print("sum of monthlyincome (attrition):", df[df["Attrition"]=="Yes"]["MonthlyIncome"].sum())

print("sum of monthlyincome:", df["MonthlyIncome"].sum())

"""## Attrition rate"""

print("Attrition rate:", f"{round((df["Attrition"]=="Yes").sum() /len(df["Attrition"])*100, 2)}%")   # Attrition_rate = 16.12%


# df.head(2)

"""## Single unmarried category shows highest attrition count"""

sns.countplot(data=df,x="MaritalStatus", hue="Attrition", palette="viridis")
plt.title("Distribution of Total Working Years by Attrition")
plt.show()

sns.histplot(data=df,x="PercentSalaryHike", hue="Attrition", bins=20, kde=True, palette="icefire")
plt.title("Distribution of Total Working Years by Attrition")
plt.show()

df.shape

"""### Exploratory Analysis Dashborad"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
fig, axes = plt.subplots(2, 3, figsize=(16, 10))

# Education vs Attrition (percent within each Education)
sns.countplot(x="Education", hue="Attrition", data=df, stat="percent", ax=axes[0, 0], palette="crest")
axes[0, 0].set_title("Attrition by Education")
axes[0, 0].set_xlabel("Education Level")
axes[0, 0].set_ylabel("Percentage (%)")

# 2) Years Since Last Promotion vs Attrition (percent within each group)
sns.countplot(x="YearsSinceLastPromotion", hue="Attrition", data=df, stat="percent", ax=axes[0, 1], palette="viridis")
axes[0, 1].set_title("Attrition by Years Since Last Promotion")
axes[0, 1].set_xlabel("Years Since Last Promotion")
axes[0, 1].set_ylabel("")

# Job Level vs Attrition (percent)
sns.countplot(x="JobLevel", hue="Attrition", data=df, stat="percent", ax=axes[0, 2], palette="mako")
axes[0, 2].set_title("Attrition by Job Level")
axes[0, 2].set_xlabel("Job Level")
axes[0, 2].set_ylabel("")

# Age distribution by Attrition
sns.histplot(x="Age", hue="Attrition", data=df, bins=15, stat="percent", kde=True, ax=axes[1, 0], palette="viridis")
axes[1, 0].set_title("Age Distribution by Attrition")
axes[1, 0].set_xlabel("Age")
axes[1, 0].set_ylabel("Percentage(%)")

# Department vs Attrition (percent)
sns.countplot(x="Department", hue="Attrition", data=df, stat="percent", ax=axes[1, 1], palette="rocket")
axes[1, 1].set_title("Attrition by Department")
axes[1, 1].set_xlabel("Department")
axes[1, 1].set_ylabel("")
axes[1, 1].tick_params(axis='x', rotation=30)

# Monthly Income distribution by Attrition (histogram)
sns.histplot(x="MonthlyIncome", hue="Attrition", data=df,stat="percent", bins=10, kde=True, ax=axes[1, 2], palette="viridis")
axes[1, 2].set_title("Monthly Income by Attrition")
axes[1, 2].set_xlabel("Monthly Income")
axes[1, 2].set_ylabel("")

plt.tight_layout()
plt.show()

df.to_csv("clean_HR_database.csv", index=False)

"""# 📊 Employee Attrition — Exploratory Data Analysis (EDA)

## 🧠 Objective
The goal of this analysis is to explore factors that contribute to **employee attrition** — i.e., employees who leave the company (`Attrition = Yes`).  
We analyze variables like **Education**, **Years Since Last Promotion**, **Job Level**, **Age**, **Department**, and **Monthly Income** to understand key churn drivers.

---

## 🧾 Dataset Overview

| Feature | Description |
|----------|--------------|
| `Attrition` | Whether an employee left (`Yes`) or stayed (`No`) |
| `Education` | Education level (1 = Below College to 5 = Doctorate) |
| `YearsSinceLastPromotion` | Years since last promotion |
| `JobLevel` | Job seniority (1 – 5) |
| `Age` | Employee age |
| `Department` | Department name |
| `MonthlyIncome` | Monthly salary (USD) |

---

## 📈 Exploratory Insights

### 1️⃣ Attrition by Education
- Most employees are at **Education Level 3 (Bachelor’s)**, which also shows the **highest attrition**.  
- Employees with advanced degrees (Master’s/Doctorate) tend to stay longer.



---

### 2️⃣ Attrition by Years Since Last Promotion
- Highest attrition occurs among employees with **0–1 years since promotion**, suggesting **career stagnation** drives churn.  
- Attrition decreases with increasing promotion intervals.



---

### 3️⃣ Attrition by Job Level
- **Job Levels 1–2** have higher attrition rates.  
- **Senior employees (Levels 4–5)** show strong retention.



---

### 4️⃣ Age Distribution by Attrition
- Younger employees (**25–35 years**) have the highest attrition.  
- Older employees (**40+**) tend to remain longer in the organization.



---

### 5️⃣ Attrition by Department
- **Research & Development** has the **largest workforce and highest attrition count**.  
- **Sales** also shows notable churn; **HR** remains low.



---

### 6️⃣ Attrition by Monthly Income
- Attrition is **highest among low-income employees (< $5,000/month)**.  
- Attrition declines as income increases — pay strongly influences retention.



---

## 🧩 Key Takeaways
✅ Younger, low-income, and junior-level employees are more likely to leave.  
✅ Recent lack of promotions is a major attrition factor.  
✅ Higher education and senior roles correlate with lower attrition.  
✅ Retention efforts should target **early-career and low-income** groups.

# Machine learning and predictive analysis
"""

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import BorderlineSMOTE

# Target & Features
y = df["Attrition"]
x = df.drop(["Attrition", "EmployeeNumber"], axis=1)

# One-hot encoding
x = pd.get_dummies(x, drop_first=True, dtype=int)

# Encode target
label = LabelEncoder()
y = label.fit_transform(y.astype(str))


# Train-test split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, stratify=y, random_state=0
)

# Scaling
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# SMOTE
sm = BorderlineSMOTE(random_state=42, kind="borderline-1")
x_train_resample, y_train_resample = sm.fit_resample(x_train_scaled, y_train)

print("Before SMOTE:\n", pd.Series(y_train).value_counts())
print("\nAfter SMOTE:\n", pd.Series(y_train_resample).value_counts())

class_labels = dict(zip(label.transform(label.classes_), label.classes_))
print(class_labels)

print("\nEncoded Target (y):")
print(y)

print("\nEncoded Feature DataFrame (X):")
display(x.head())

"""### Model selection"""

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

from xgboost import XGBClassifier
from catboost import CatBoostClassifier


models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42),

    "Decision Tree": DecisionTreeClassifier(class_weight="balanced", random_state=42),

    "Random Forest": RandomForestClassifier(n_estimators=200, max_depth=6, class_weight="balanced", random_state=42),

    "Gradient Boosting": GradientBoostingClassifier(n_estimators=200, learning_rate=0.05, max_depth=3, random_state=42),

    "Naive Bayes": GaussianNB(),

    "XGBoost": XGBClassifier(n_estimators=200, max_depth=6,objective="binary:logistic",eval_metric="logloss",random_state=42),

    "CatBoost": CatBoostClassifier(iterations=200, max_depth=6, loss_function="Logloss", random_state=42, verbose=False)}

class_labels = {
    0: "Class 0 (No Attrition)",
    1: "Class 1 (Attrition)"
}


for name, model in models.items():
    print(f"\n{'='*10} {name} {'='*10}")

    # Train
    model.fit(x_train_resample, y_train_resample)

    # Predictions
    y_train_pred = model.predict(x_train_resample)
    y_test_pred  = model.predict(x_test_scaled)

    # Probabilities
    y_train_prob = model.predict_proba(x_train_resample)
    y_test_prob  = model.predict_proba(x_test_scaled)

    # Loss & Accuracy
    print(
        f"Train Loss: {log_loss(y_train_resample, y_train_prob):.3f} | "
        f"Test Loss: {log_loss(y_test, y_test_prob):.3f}")


    print(
        f"Train Accuracy: {accuracy_score(y_train_resample, y_train_pred):.3f} | "
        f"Test Accuracy: {accuracy_score(y_test, y_test_pred):.3f}")


    # Per-class metrics
    precision = precision_score(y_test, y_test_pred, average=None, zero_division=0)
    recall    = recall_score(y_test, y_test_pred, average=None, zero_division=0)
    f1        = f1_score(y_test, y_test_pred, average=None, zero_division=0)
    roc_auc = roc_auc_score(y_test, y_test_prob[:, 1])


    print("\nPer-Class Metrics:")
    for i in range(len(precision)):
        print(
            f"{class_labels[i]} | "
            f"Precision={precision[i]:.3f}  "
            f"Recall={recall[i]:.3f}  "
            f"F1={f1[i]:.3f}")


    # ROC-AUC
    print(f"\nROC-AUC: {roc_auc_score(y_test, y_test_prob[:, 1]):.3f}")

    # Confusion Matrix & Report
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_test_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_test_pred, zero_division=0))

"""## Finetuned logistic regression"""

Logistic_tuned = LogisticRegression(
    solver="liblinear",
    penalty="l2",
    C=0.5,
    class_weight="balanced",
    max_iter=2000,
    random_state=0
)

# Train
Logistic_tuned.fit(x_train_resample, y_train_resample)

# Probabilities
y_train_prob = Logistic_tuned.predict_proba(x_train_resample)
y_test_prob  = Logistic_tuned.predict_proba(x_test_scaled)


# Predictions
y_train_pred = Logistic_tuned.predict(x_train_resample)
y_test_pred  = Logistic_tuned.predict(x_test_scaled)


# Log Loss
train_log_loss = log_loss(y_train_resample, y_train_prob)
test_log_loss  = log_loss(y_test, y_test_prob)

print(f"Train Log Loss: {train_log_loss:.4f}")
print(f"Test  Log Loss: {test_log_loss:.4f}")


# Accuracy
print("Train accuracy:", accuracy_score(y_train_resample, y_train_pred))
print("Test accuracy :", accuracy_score(y_test, y_test_pred))


# Per-class metrics
precision = precision_score(y_test, y_test_pred, average=None, zero_division=0)
recall    = recall_score(y_test, y_test_pred, average=None, zero_division=0)
f1        = f1_score(y_test, y_test_pred, average=None, zero_division=0)

print("\nPer-Class Metrics:")
for i in range(len(precision)):
    print(
        f"Class {i} | "
        f"Precision={precision[i]:.3f}  "
        f"Recall={recall[i]:.3f}  "
        f"F1={f1[i]:.3f}"
    )


# ROC-AUC (positive class)
y_probability = y_test_prob[:, 1]
print("\nROC AUC :", roc_auc_score(y_test, y_probability))



# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred, zero_division=0))

"""## Finetuned randomforest"""

from sklearn.ensemble import RandomForestClassifier

RandomForest_tuned = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=15,
    class_weight="balanced",
    random_state=42
)

RandomForest_tuned.fit(x_train_resample, y_train_resample)

# Probabilities
y_train_prob = RandomForest_tuned.predict_proba(x_train_resample)
y_test_prob  = RandomForest_tuned.predict_proba(x_test_scaled)


# Predictions
y_train_pred = RandomForest_tuned.predict(x_train_resample)
y_test_pred  = RandomForest_tuned.predict(x_test_scaled)


# Log Loss
train_log_loss = log_loss(y_train_resample, y_train_prob)
test_log_loss  = log_loss(y_test, y_test_prob)

print(f"Train Log Loss: {train_log_loss:.4f}")
print(f"Test  Log Loss: {test_log_loss:.4f}")


# Accuracy
print("Train accuracy:", accuracy_score(y_train_resample, y_train_pred))
print("Test accuracy :", accuracy_score(y_test, y_test_pred))


# Per-class metrics
precision = precision_score(y_test, y_test_pred, average=None, zero_division=0)
recall    = recall_score(y_test, y_test_pred, average=None, zero_division=0)
f1        = f1_score(y_test, y_test_pred, average=None, zero_division=0)

print("\nPer-Class Metrics:")
for i in range(len(precision)):
    print(
        f"Class {i} | "
        f"Precision={precision[i]:.3f}  "
        f"Recall={recall[i]:.3f}  "
        f"F1={f1[i]:.3f}"
    )


# ROC-AUC (positive class)
y_probability = y_test_prob[:, 1]
print("\nROC AUC :", roc_auc_score(y_test, y_probability))


# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred, zero_division=0))

"""Random Forest was chosen for deployment due to higher precision, stronger probability separation, and better handling of non-linear attrition drivers, while recall requirements were satisfied through threshold tuning. Logistic Regression was retained as a benchmark and recall-oriented alternative

### Optimal Attrition Probability Threshold
"""

from sklearn.metrics import roc_curve

# Compute ROC
fpr, tpr, thresholds = roc_curve(y_test, RandomForest_tuned.predict_proba(x_test_scaled)[:, 1])  #False Positive Rate (fpr), True Positive Rate (tpr)

# Find optimal threshold (Youden's J)
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]

print(f"Optimal Attrition Probability Threshold: {optimal_threshold:.3f}")

""" ###  Top 10 Most Important Features Influencing Attrition

"""

importances = pd.Series(RandomForest_tuned.feature_importances_,index=x.columns)
# Top 10 features
top10 = (importances.sort_values(ascending=False).head(10).reset_index())
print(top10)

top10.columns = ["Feature", "Importance"]

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(data=top10, y="Feature", x="Importance", palette="viridis")
plt.title("Top 10 Features Influencing Attrition (Random Forest)", fontsize=14, fontweight="bold")
plt.xlabel("Feature Importance Score", fontsize=12)
plt.show()

"""### ROC Curve"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label='ROC Curve')
plt.plot([0,1], [0,1], linestyle='--', color='gray')
plt.scatter(fpr[optimal_idx], tpr[optimal_idx], color='red', label=f'Optimal Threshold = {optimal_threshold:.2f}')
plt.title("ROC Curve — Attrition Model")
plt.xlabel("False Positive Rate (1 - Specificity)")
plt.ylabel("True Positive Rate (Sensitivity)")
plt.legend()
plt.show()

"""### Decision Boundary"""

# Scale full dataset
x_scaled = scaler.transform(x)

# Predict numeric class (0 / 1)
predicted_numeric = RandomForest_tuned.predict(x_scaled)

# Decode back to original labels ("Yes" / "No")
df["Predicted_Attrition"] = label.inverse_transform(predicted_numeric)

# Get attrition probability (class 1)
df["Attrition_Probability"] = RandomForest_tuned.predict_proba(x_scaled)[:, 1]

# Plot
plt.figure(figsize=(8, 5))
sns.kdeplot(
    data=df,
    x="Attrition_Probability",
    hue="Attrition",
    fill=True
)

plt.axvline(optimal_threshold, color="red", linestyle="--")

plt.title("Attrition Probability Distribution by Actual Status")
plt.xlabel("Attrition Probability")
plt.ylabel("Density")
plt.show()

"""## Actual vs predicted results"""

df["Predicted_Attrition_Adjusted"] = np.where(
    df["Attrition_Probability"] >= optimal_threshold, "Yes", "No"
)

df[["EmployeeNumber", "Attrition", "Predicted_Attrition_Adjusted", "Attrition_Probability"]].head(15)

"""### New employee record to predict"""

new_employee = pd.DataFrame([
    {
        "Age": 28,
        "BusinessTravel": "Travel_Rarely",
        "DailyRate": 1100,
        "Department": "Sales",
        "DistanceFromHome": 5,
        "Education": 3,
        "EducationField": "Marketing",
        "EmployeeCount": 1,
        "EmployeeNumber": 9999,
        "EnvironmentSatisfaction": 3,
        "Gender": "Male",
        "HourlyRate": 70,
        "JobInvolvement": 3,
        "JobLevel": 2,
        "JobRole": "Sales Executive",
        "JobSatisfaction": 3,
        "MaritalStatus": "Single",
        "MonthlyIncome": 4500,
        "MonthlyRate": 15000,
        "NumCompaniesWorked": 2,
        "Over18": "Y",
        "OverTime": "Yes",
        "PercentSalaryHike": 13,
        "PerformanceRating": 3,
        "RelationshipSatisfaction": 3,
        "StandardHours": 80,
        "StockOptionLevel": 1,
        "TotalWorkingYears": 6,
        "TrainingTimesLastYear": 3,
        "WorkLifeBalance": 2,
        "YearsAtCompany": 3,
        "YearsInCurrentRole": 2,
        "YearsSinceLastPromotion": 1,
        "YearsWithCurrManager": 2
    },
    {
        "Age": 35,
        "BusinessTravel": "Non-Travel",
        "DailyRate": 900,
        "Department": "Research & Development",
        "DistanceFromHome": 2,
        "Education": 4,
        "EducationField": "Life Sciences",
        "EmployeeCount": 1,
        "EmployeeNumber": 10000,
        "EnvironmentSatisfaction": 4,
        "Gender": "Female",
        "HourlyRate": 60,
        "JobInvolvement": 4,
        "JobLevel": 3,
        "JobRole": "Research Scientist",
        "JobSatisfaction": 4,
        "MaritalStatus": "Married",
        "MonthlyIncome": 7200,
        "MonthlyRate": 14000,
        "NumCompaniesWorked": 1,
        "Over18": "Y",
        "OverTime": "No",
        "PercentSalaryHike": 11,
        "PerformanceRating": 3,
        "RelationshipSatisfaction": 4,
        "StandardHours": 80,
        "StockOptionLevel": 2,
        "TotalWorkingYears": 12,
        "TrainingTimesLastYear": 4,
        "WorkLifeBalance": 3,
        "YearsAtCompany": 7,
        "YearsInCurrentRole": 5,
        "YearsSinceLastPromotion": 2,
        "YearsWithCurrManager": 5
    },
    {
        "Age": 24,
        "BusinessTravel": "Travel_Frequently",
        "DailyRate": 1300,
        "Department": "Sales",
        "DistanceFromHome": 15,
        "Education": 2,
        "EducationField": "Marketing",
        "EmployeeCount": 1,
        "EmployeeNumber": 10001,
        "EnvironmentSatisfaction": 2,
        "Gender": "Male",
        "HourlyRate": 80,
        "JobInvolvement": 2,
        "JobLevel": 1,
        "JobRole": "Sales Representative",
        "JobSatisfaction": 2,
        "MaritalStatus": "Single",
        "MonthlyIncome": 3000,
        "MonthlyRate": 18000,
        "NumCompaniesWorked": 3,
        "Over18": "Y",
        "OverTime": "Yes",
        "PercentSalaryHike": 15,
        "PerformanceRating": 3,
        "RelationshipSatisfaction": 2,
        "StandardHours": 80,
        "StockOptionLevel": 0,
        "TotalWorkingYears": 3,
        "TrainingTimesLastYear": 2,
        "WorkLifeBalance": 1,
        "YearsAtCompany": 1,
        "YearsInCurrentRole": 1,
        "YearsSinceLastPromotion": 0,
        "YearsWithCurrManager": 1
    }
])

"""### Match Columns to the Model’s Input and predict the outcome"""

import pandas as pd
import numpy as np

# Columns dropped during training
cols_to_drop = ["EmployeeNumber", "EmployeeCount"]

x_new = new_employee.copy()

# 1. Remove same columns as training
for c in cols_to_drop:
    if c in x_new.columns:
        x_new = x_new.drop(columns=c)

# 2. One-hot encode
x_new = pd.get_dummies(x_new, drop_first=True)

# 3. Align with training columns
x_new = x_new.reindex(columns=x.columns, fill_value=0)

# 4. Scale
x_new_scaled = scaler.transform(x_new)

# 5. Predict class and probability
pred_class = RandomForest_tuned.predict(x_new_scaled)
pred_prob = RandomForest_tuned.predict_proba(x_new_scaled)[:,1]


print("Predicted Attrition:", pred_class)
print(f"Attrition Probability: {pred_prob}")    ##### Attrition dont seem to happen employee is Active / Retained.

"""# 🤖 Employee Attrition Prediction — Machine Learning Report

## 🧠 Project Objective
The goal of this machine learning project is to **predict employee attrition** (whether an employee is likely to leave the company) using HR data.  
This analysis helps HR teams identify high-risk employees and design targeted retention strategies.

---

## 🧾 Dataset Overview
The dataset contains **1,470 employee records** and **38 features**, including:

| Feature | Description |
|----------|--------------|
| Age | Employee age |
| Department | Functional area (Sales, R&D, HR) |
| JobLevel | Seniority level (1–5) |
| MonthlyIncome | Salary amount |
| YearsAtCompany | Employee tenure |
| OverTime | Whether employee works overtime (Yes/No) |
| JobSatisfaction, WorkLifeBalance | Categorical satisfaction scores |
| Attrition | Target variable — “Yes” (left) / “No” (stayed) |

---

## ⚙️ Data Preprocessing Steps
1. **Missing Values:** Dataset had no missing records.  
2. **Encoding:**  
   - Used `pd.get_dummies()` for categorical features.  
   - Encoded target (`Attrition`) using `LabelEncoder` (Yes → 1, No → 0).  
3. **Scaling:**  
   - Applied `StandardScaler` to normalize numeric features.  
4. **Train/Test Split:**  
   - 80 % training / 20 % testing (with stratification).  
5. **Imbalance Handling:**  
   - Used **SMOTE** to oversample minority class and balance attrition = Yes/No.

---

## 🧩 Model Training
**Algorithm Used:** Random Forest Classifier  

**Why Random Forest?**  
- Handles mixed (categorical + numeric) data well  
- Resistant to overfitting  
- Provides interpretable feature importances

---

## 📊 Model Performance

| Metric | Score |
|---------|-------|
| ** Test Accuracy** | 0.87 |
| ** Train Accuracy** | 0.94|
| **Recall **  | 0.87 |
| **F1 Score** | 0.86|
| **ROC-AUC** | 0.80 |




✅ **Interpretation:**  
The model correctly identifies most employees who will leave while keeping false alarms low.  
ROC-AUC ≈ 0.80 indicates **strong discrimination ability** between leavers and stayers.

---

## 📈 Optimal Decision Threshold
Using the **ROC curve**, the optimal probability threshold was found at:

> 🔹 ** 0.36**

Employees with predicted attrition probability ≥ 0.40 are classified as **likely to leave**.



---

## 📉 Probability Distribution
This plot shows predicted attrition probabilities for both groups.  
- 🟧 Orange = Stayed employees (Attrition = No)  
- 🔵 Blue = Left employees (Attrition = Yes)  
- 🔴 Dashed line = Decision threshold (0.28)



---

## 🧮 Top 10 Most Influential Features
| Rank | Feature                | Importance |
|------|------------------------|------------|
| 1️⃣  | OverTime_Yes           | 0.145      |
| 2️⃣  | StockOptionLevel       | 0.075      |
| 3️⃣  | JobSatisfaction        | 0.060      |
| 4️⃣  | MaritalStatus_Single   | 0.050      |
| 5️⃣  | YearsAtCompany         | 0.045      |
| 6️⃣  | Age                    | 0.042      |
| 7️⃣  | MonthlyIncome          | 0.040      |
| 8️⃣  | TotalWorkingYears      | 0.038      |
| 9️⃣  | JobInvolvement         | 0.036      |
| 🔟   | YearsWithCurrManager   | 0.035      |


🧠 **Key Insight:**  
Employees working **overtime**, with **low satisfaction** or **low stock options**, are more prone to leave.

---

## 🧩 Final Model Interpretation

| Probability Range | Risk Level | HR Action |
|--------------------|-------------|------------|
| 0.00 – 0.28 | 🟢 Low Risk | Normal monitoring |
| 0.28 – 0.50 | 🟡 Moderate Risk | Review workload / satisfaction |
| 0.51 – 0.70 | 🟠 High Risk | Engage proactively |
| 0.71 – 1.00 | 🔴 Very High Risk | Immediate retention focus |

---

## 💡 Key Takeaways
- **OverTime** and **Job Satisfaction** are major attrition drivers.  
- **Younger**, **single**, **low-income** employees are more likely to leave.  
- A **0.40 cutoff** offers the best balance between recall and precision.  
- The model can support **data-driven HR decisions** for employee retention.

---

## 🧠 Tools & Libraries
`Python · pandas · numpy · matplotlib · seaborn · scikit-learn · imbalanced-learn`

---

## ✨ Conclusion
The Random Forest attrition model achieves strong predictive accuracy and interpretability.  
By identifying at-risk employees early, organizations can **reduce turnover**, improve **employee engagement**, and strengthen **HR strategy** through evidence-based analytics.

---

📍 *End of Machine Learning Report*

"""

